name: Data
on:
  push:
    branches:
      - master
      - beta
      - stable
  pull_request:
    branches:
      - master
      - beta
      - stable
jobs:
  Any_Any:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log environment
        run: env

      - name: Install additional tools
        run: >-
          sudo apt install
          dos2unix
          gettext

      - name: Update version
        run: |
          fsbuild/version --update

      - name: Bootstrap
        run: fsbuild/bootstrap

      - name: Build
        run: |
          pipenv run fsbuild/build

      - name: Bundle
        run: |
          pipenv run fsbuild/bundle

      - name: Archive
        run: |
          fsbuild/archive

      - uses: actions/upload-artifact@v2
        with:
          name: Any_Any
          path: fsbuild/_dist/*

      - name: Upload build to Dropbox folder
        if: >-
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/stable'
        run: |
          python3 -m pip install dropbox
          fsbuild/upload
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
